FROM gcc:12.2.0
# because source isn't available and ~/.xmake/profile can't run on sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt update
RUN apt upgrade -y
# because xmake can't get it for ARM64
RUN apt install -y cmake

# install Xmake
RUN bash <(curl -fsSL https://xmake.io/shget.text)

# allow xmake as root
ENV XMAKE_ROOT y

WORKDIR /app

# cleanup
RUN rm -rf /tmp/.xmake*

ENTRYPOINT bash -c "source ~/.xmake/profile && $0 $@"
CMD [ "xmake" ]
